# Generated by Django 3.1.1 on 2020-09-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_step_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Text',
        ),
    ]
